### ISSUE TITLE
谢谢库主。谁能提供一个跑得快一些的tasklist.json吗？

### ISSUE THREAD

**Issue by Ma-minghao** [Zirconium233/yunForNewVerison#10]
或者提供自己杜撰的方法😬😬😬

**Comment by Ma-minghao** [comment]
最快配速是3:00，再快就不能提交。我记得一学期平均配速6:00以内是满分。

**Comment by Zirconium233** [comment]
接力或者骑车刷一个快的，或者也有另一个方法：
```json
"recordMileage": 2.21,
        "recodePace": 7.86,
        "recodeCadence": 132,
        "recodeDislikes": 2,
        "duration": 1044,
        "pointsList": [
            {
                "id": 0,
                "point": "117.20590949247465,31.773745665863856",
                "speed": 10.48,
                "runStatus": 1,
                "runRecordId": 0,
                "runTime": "10",
                "isFence": "Y",
                "runStep": "20",
                "runMileage": "11.903182983398438"
            },
```
把所有点的`runtime`和`speed`等比例改小，总的`duration`和`recodePace`也等比例减小，最后控在5分钟就可以。

**Comment by Ma-minghao** [comment]
这一块也是tasklist里的，marked是监测在不在跑区内吗？这部分要不要改啊？
```
"manageList": [
            {
                "point": "117.206317,31.773892",
                "marked": "Y",
                "index": 1
            },
            {
                "point": "117.208436,31.773412",
                "marked": "N",
                "index": 1
            },
            {
                "point": "117.205992,31.773411",
                "marked": "Y",
                "index": 0
            },
            {
                "point": "117.20632,31.774412",
                "marked": "N",
                "index": 3
            },
            {
                "point": "117.208752,31.773909",
                "marked": "N",
                "index": 4
            }
        ]
```

**Comment by Ma-minghao** [comment]
我有一个非常快的历史记录，已经抓包了，但是按教程用SM2解密不了
`"lUhtZ5XbewcYUTfeJ8IPkNlwXfg61O8kQLxTlnWeJf4VlaUmOq2F8X1yAXoxq0nqCvOKTzEMXw1dnjkmREz7yHptT/V4mUqpmzGh287lCZgUAMHzCG1jo1ZoOpPUgjRBCv9XCrD7sjIkOPVx0OZcHiL9huVko52cLr/0S8n5zFt3SKcxwN9e6pX0AJdHg4LIX8RIt89xhhU6wAwc6WpBdghftFnCyPabpHI6Avnr9eQ4z6S6dp7MeZaJsYylRu4+FxadhMLlIssrcyeVqe0D95nejR9PBWmltUMYPaJzhj3UKQPxKBm3dDFcxUbdbJfFXm3lz8Bopry6YzxrsG/8hSXZZVMB7k/1VZx+rIh9VWpI19PEcs4Ys2EJnx/diphmLe70BwnFO/RJhoz7NFcp3gFdwVMMvjkdEjhQb0CkWaP+KQp3RkXqO44Jha0aScwP2de08WUGb3vebOruzXVf2yR9Hoi8LBmqDcf/zDck5idUpkawARUiuphNUf2QJB5sTErp1suvGWCicT7CPWaZ1YocA1aP8ZpJsmAX+WAJ5v9LNkQRlA1VavzD1unytGvOrsBdKTj2vR9V5950nq2vU4GvLVWs90MX4OCbH890L25mt5i0ug3HNfghAEHVZMN3KjqhvusJM3uBy59Zsxt3Rn5Rx1mkh8j3TooSy+VSjoE3T1NM22e21kAZv5AkJCj6XKEeKETAvHAPbFbY79xdbOMkUSwdJwSLsf7YNsY4PEXngJyogg1zh9XN1SIg7iOsYNeyK5tSgTDPrpCMx3LHxIBeK2tP6psFRzJs8v3YkdL+7bM5vSANKmfYkBZF4pYCgzJUnaAamSaB66ZjytEiE/Wf8I86r0gvQiq0qk5t1gKVD3eKKMhn6FKJvLY9wHjIFeKdqBqQ/YahVWt+CcuUZSSZxnQm7bMWsK6hSsoovooDRICMUAg6E1NNcSAG8ulsvJxarjwf4AJoWkG4tAUNdjrcCzPjYN9tpri/cgafc8IAcyvJzp/YvSTCFnIDerh/A9bxy6AcHE17+ygj3QwwHJVy8KV6BsLYhDI+w/rua1dJeqRgRqToQt+twgNhPEzF6NXCIjK1GLfQS6P/mLgfdiLqtlwBurXtRiLTnyFZ0Hiyjq7QTxIzIxv/65UNP/93DG3e5lgHNQtJdWLHY+RzSLFAMBG6uokHCAwFqmCAH+Fqja4qLTxKIByRWjXFTyvs752eUxcXQ4HKHRbglUdY6k5Bn5349z05MTk3WH5zP5icLbGJNy4DuPjH9aBeHPzH7XYfrdNhJ/8xJFTDitoelQ=="`

**Comment by Zirconium233** [comment]
这么短一眼就不是历史记录，应该是其他数据，只有历史记录这样的长文才有gzip加密。你把代码里面的gzip删了解密再这个就可以成功，不过没什么必要。

**Comment by Zirconium233** [comment]
已经实现了自动加速小程序，python pace_changer.py，输入All和random即可。
