### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by thersir** [Zirconium233/yunForNewVerison#11]
大佬，我用工具解密时有问题，是用response body和cipherkey吗
![image](https://github.com/Zirconium233/yunForNewVerison/assets/162893459/6bd9702e-6ecb-459e-8696-8dbb3bc42d6d)
![c710c2c77f40f8d509a42bbf83d731d8](https://github.com/Zirconium233/yunForNewVerison/assets/162893459/fab2a50a-f8c8-46e1-8a89-7c90b54887d4)
![55dd1d4ebb23392eed6f5cbe15681719](https://github.com/Zirconium233/yunForNewVerison/assets/162893459/f693768e-4088-4a1b-9e6b-a620c10ade85)

**Comment by Zirconium233** [comment]
盲猜data填的不完整，因为太长剪切板截断了，或者不小心把引号打进去了这样，也可以试试看把gzip关掉，看看结尾和开头能不能对应上。如果还不行试试看去网页上解，验证一下是不是我工具的问题。

**Comment by thersir** [comment]
data没问题，网页上解密还不是很懂，用的是config.ini里自带的公钥私钥吗
![image](https://github.com/Zirconium233/yunForNewVerison/assets/162893459/042bca5f-d2c0-4390-b6b4-ae15e8c6b546)

**Comment by Zirconium233** [comment]
是的，但你网页提示的是invalid cipher text，也就是你下面的CipherKey不对(大概率是base64编码错误，不太可能是解密错误)，解密不出来。你检查一下是不是少了字符什么的，或者直接重新抓一次换一个看看能不能解密。

**Comment by thersir** [comment]
大佬您好，我没有学过python，出现这个报错要怎么解决
![image](https://github.com/Zirconium233/yunForNewVerison/assets/162893459/7e0f620d-251c-4c8a-a7a5-42478abd943c)

**Comment by Zirconium233** [comment]
你有可能是版本不对，或者是开始时候选的选项不对。打表模式没有生成manageList因为不需要，使用表格的https://github.com/Zirconium233/yunForNewVerison/blob/7e0634cb0b11792fb65beedea3b349d543dd05fb/main.py#L440
但是你的使用的却是 `self.manageList`
https://github.com/Zirconium233/yunForNewVerison/blob/7e0634cb0b11792fb65beedea3b349d543dd05fb/main.py#L490
检查上面这行是不是改动了

**Comment by thersir** [comment]
谢谢大佬 改回来之后就好了
