### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wsmh** [Zirconium233/yunForNewVerison#12]
![QQ截图20240514142015](https://github.com/Zirconium233/yunForNewVerison/assets/144468819/389f223d-4eba-446b-bb5c-abc2609e5c38)
这种情况该怎么办

**Comment by Zirconium233** [comment]
base64编码错误，就是你复制的有问题，可能多打了引号，或者漏了什么

**Comment by wsmh** [comment]
佬，上一步成功了，但是进行响应体解码的时候怎么这样了
![image](https://github.com/Zirconium233/yunForNewVerison/assets/144468819/ba8da800-ceb0-4256-9679-7f1007dc8130)

**Comment by wsmh** [comment]
OK我懂了，大佬牛比

**Comment by Zirconium233** [comment]
上面key填的密钥没问题，下面接码的包体你要复制进去，你传了一个“结果如下”进去解密当然是报错，base64也告诉你了输入的包含非ascii字符
