### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by dioxide-orange** [Zirconium233/yunForNewVerison#13]
这次也cd到目录了，还是有问题
![image](https://github.com/Zirconium233/yunForNewVerison/assets/160996568/93741f86-2f9d-4e22-adc5-3750dbdacb31)
求助

**Comment by Zirconium233** [comment]
https://github.com/Zirconium233/yunForNewVerison/blob/7e0634cb0b11792fb65beedea3b349d543dd05fb/README.md?plain=1#L39
记得安装依赖

**Comment by dioxide-orange** [comment]
> https://github.com/Zirconium233/yunForNewVerison/blob/7e0634cb0b11792fb65beedea3b349d543dd05fb/README.md?plain=1#L39
> 
> 
> 记得安装依赖

噗噗噗，mad我好傻啊🤣
