### ISSUE TITLE
3.3.1版本解密后的文件

### ISSUE THREAD

**Issue by laizhangtu** [Zirconium233/yunForNewVerison#15]
佬，现在的data解密后是这样的，仍然能用吗？
![problem](https://github.com/user-attachments/assets/a8e1cd30-fcd1-4f81-a86b-6e3e0412362c)

**Comment by Zirconium233** [comment]
包体内容好像有变，额外上了时间记录，不过好消息是加密方式没改，能正常解密，那就不会很麻烦。

问一个问题：老版本的云运动软件还能用吗？
- 如果不是强制要求升级，旧版本的服务器应该就不会查，post包的时候版本用定死的3.0.0就行了；
- 如果强制要求升级了，就重新抓一轮包，找不同在把时间戳加上去伪装就行了。

这个是小改动，纯改逻辑就能伪装，难度应该不大。我后面有空会去适配新版本，如果老版本不能用而且你比较急提前搞定了，欢迎直接提pr

**Comment by laizhangtu** [comment]
3.0.0版本软件还能用，但抓包的数据也有时间记录，可能是因为我们学校才开始用云运动？
![problem0910](https://github.com/user-attachments/assets/f84b04d6-fd72-4992-832a-786de526a8aa)

**Comment by Cc3374** [comment]
> 好的，谢谢大佬

哥能不能加个好友（q3414859638）我想请教一下解密问题，我解密响应体里的内容一直报错解密不出来，响应体里的内容我都检查几遍了，大佬提供的代码和工具都试过了

![Image](https://github.com/user-attachments/assets/e072338f-a0cf-43b6-943a-af2d6885ebfb)

![Image](https://github.com/user-attachments/assets/fc7933ac-4d0c-4e48-8ac3-44ccd02d9f1d)

**Comment by Zirconium233** [comment]
报错说的很明显了，sm4解密返回的不是gzip编码。所以应该是格式处理问题，比如可能返回的数据没有gzip压缩过。能解密不报错说明密钥是对的，主目录有一个jupyter notebook解密流程写的很清楚。还有我还有其他事情要干，只能保证脚本至少在我这里能跑通，不可能无限制帮别人debug的。

**Comment by Cc3374** [comment]
感谢大佬抽空亲自回复，我今晚再试试

**Comment by Cc3374** [comment]
大佬，我想再问一下我这个好像解密出来了，但是显示服务异常是大概是什么原因就是这个历史路线接口/run/crsReocordInfo

![Image](https://github.com/user-attachments/assets/62ca2e69-b062-461c-837d-920b6c27e0fe)

**Comment by Cc3374** [comment]
大佬我想再请问一下，我好像解密出来了，但是他报500,大概是什么问题啊

![Image](https://github.com/user-attachments/assets/ba864958-2501-4c40-9b07-f03998e9696c)

![Image](https://github.com/user-attachments/assets/bc4bddbd-d83d-4ede-ae1c-705ee446d223)

**Comment by Zirconium233** [comment]
post 给 500 基本上就是通讯密钥问题，详见 #48 。还有解密与post相关问题基本上都被提过一次issue了，你可以直接去其他issue里面获取解决方案，没必要在closed的issue里面追问。
