### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Ir-Inu** [Zirconium233/yunForNewVerison#16]
请问config里面的map_key怎么填...试了一个小时了,一直没法开始,显示的错误信息是'data',求助
![屏幕截图 2024-09-12 224231](https://github.com/user-attachments/assets/b86b2941-1344-4fed-9717-6969edfb39a6)

**Comment by Ir-Inu** [comment]
![屏幕截图 2024-09-12 224529](https://github.com/user-attachments/assets/f2318c33-dff5-4d09-91eb-eedf95b675de)

**Comment by Zirconium233** [comment]
我提供了8套记录，如果你是一个校区的可以直接使用，如果不是就只能申请key然后导航，或者抓室友历史记录包，具体教程可以看readme。还有这个repo许多地方调的不是很好，原本就是打算做一个能跑的demo，内容都是后面慢慢加的，实话说不是很推荐纯小白使用，强烈建议有基础时候自己改着用。

**Comment by Zirconium233** [comment]
> > > 去高德地图那边申请一个服务api。同时我不建议使用导航模式，因为那些老东西效果不好所以我自己也不用，已经6个月没维护了，跑一遍然后打表是比较方便的做法。
> > 
> > 
> > 就是说我要先自己去跑一次，再用打表模式吗?(CS小白,真的啥也不会,感谢)
> 
> 每次退出重登录，token，sign，utc都会发生改变，最好就是一次登录，抓完包不再登出。你可以重新抓下包试试。

最新版本无需填写sign和utc参数，脚本会自己生成时间戳了。不知道是不是即时utc的缘故，finish包已经不会返回500服务器异常了。
![image](https://github.com/Zirconium233/yunForNewVerison/blob/master/image/pass.png)
