### ISSUE TITLE
关于打表模式下的runstep

### ISSUE THREAD

**Issue by ANormalDD** [Zirconium233/yunForNewVerison#18]
在我使用打表模式后，查询该次运动记录所返回的抓包结果中pointsList中不存在runStep的key。

**Comment by ANormalDD** [comment]
这个是不必在意的部分吗

**Comment by Zirconium233** [comment]
关于pointlist里面有什么，这取决于你当时发包时候给了什么、软件版本和有没有给权限等，比如3.0.0以前只需要点数据即可，抓那时候的pointlist很可能只有点；3.3.1也变了一次，之后的多了utc数据。

这些确实不重要，只要有总的里程和时间，总步数数据等，每个点的都可以计算出来，或者生成出来。
