### ISSUE TITLE
佬，cipherkey解密总是不对

### ISSUE THREAD

**Issue by Lampotaku** [Zirconium233/yunForNewVerison#19]
查了复制，引号也去掉了，等号没有手动删，直接用源文件复制过来的，还是提示不对
![QQ20241012-210347](https://github.com/user-attachments/assets/e3acaec6-ecaf-4817-85e4-7215b50f5e1e)

用的cipherkey是crsReocordInfo这个包里的，我看了一下好像就这个符合
![IMG_7950](https://github.com/user-attachments/assets/863d3a09-ebc4-40ed-a4d0-517e5c0ddb0c)
![IMG_7949](https://github.com/user-attachments/assets/c7303554-e7d3-444f-8762-b251f01bac54)

**Comment by Zirconium233** [comment]
报错说的很明白了，你复制进去的是无效的base64编码，也就是格式问题。不是引号和等号的话，考虑检查一下有没有多余空格、复制出错、拼接出错、软件自己乱加后缀等等可能的问题

**Comment by Lampotaku** [comment]
> 报错说的很明白了，你复制进去的是无效的base64编码，也就是格式问题。不是引号和等号的话，考虑检查一下有没有多余空格、复制出错、拼接出错、软件自己乱加后缀等等可能的问题

不行，iOS和安卓端的软件都尝试过..还是报无效 是不是改了加密方式？

**Comment by Zirconium233** [comment]
首先可以确定的是加密方式没变，因为我上一秒还在用这个逻辑跑步。而且base64编码错误意味着你的输入不合法，压根没到解密这一步就卡掉了。

**Comment by Lampotaku** [comment]
对，但是不管怎么抓包，换软件始终还是输入不合法 (
例如现在我输入的key是BPRumotMHfbdrxiJ4oHjD1ymEOj+XOcabGTug7Wup9QjwWb81wCnRlXI99fhM/xjbMBXlRGt4jwyXuMYZXKdQN0qbBp2HCGOmFLK4X1KuRtx4iRskC03yX9a+1ObX8jkACeYSg/NK6ILx/fVIwWXQupBFJmRH917Mg==，依旧不合法
![QQ20241012-214354](https://github.com/user-attachments/assets/a9f5a95f-beb5-40ee-8191-1e0cbcb66ecc)

**Comment by Zirconium233** [comment]
![image](https://github.com/user-attachments/assets/d84b1e49-7285-49ed-9a6e-912986460da9)
我就没有问题，检查一下你输入的公钥和私钥。

**Comment by Lampotaku** [comment]
> ![image](https://private-user-images.githubusercontent.com/148327878/375961726-d84b1e49-7285-49ed-9a6e-912986460da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDExNDgsIm5iZiI6MTcyODc0MDg0OCwicGF0aCI6Ii8xNDgzMjc4NzgvMzc1OTYxNzI2LWQ4NGIxZTQ5LTcyODUtNDllZC05YTZlLTkxMjk4NjQ2MGRhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMzQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTMxYWE4NGI5MjhhOTgxNDczZTA1NTA4NTQ2Y2ZhZTkwN2U1MWRiYWRiMjJiODgzYTVmZTcyMWRjMTllM2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NXTnXSMZWbAd4G-hqzeyiu7KPP0lPNupC-IS8qSa1y4) 我就没有问题，检查一下你输入的公钥和私钥。

我去，红温了半天，私钥那里多复制了一个等号..我眼是真的瞎了，谢谢大佬
