### ISSUE TITLE
运行 mitmweb -p 8080 -s proxy.py时的报错

### ISSUE THREAD

**Issue by coffee-xzm** [Zirconium233/yunForNewVerison#24]
![clipboard-image-1729770737](https://github.com/user-attachments/assets/d7437507-1a19-4c3a-a6e7-d3e7ed38252b)

![clipboard-image-1729770765](https://github.com/user-attachments/assets/48ff5e6c-83e1-4e82-bb40-edb750553593)

求大佬解答，没搞懂是怎么索引超出范围的

**Comment by Zirconium233** [comment]
首先这个功能不是我做的，是来自别人的pr，我并不清楚mitmweb的调度。我个人是提倡直接抓包的，毕竟写死代码很容易因为风吹草动就挂了。不过看你这个报错，似乎是resquest报错连带导致java解密报错，最后导致output空了，所以后面index out of range。排查的话首先检查一下网络和登录等，解决不了再考虑print中间输出，看看再哪一步挂了，当然推荐你直接问[ANormal](https://github.com/ANormalDD)

**Comment by coffee-xzm** [comment]
> 首先这个功能不是我做的，是来自别人的pr，我并不清楚mitmweb的调度。我个人是提倡直接抓包的，毕竟写死代码很容易因为风吹草动就挂了。不过看你这个报错，似乎是resquest报错连带导致java解密报错，最后导致output空了，所以后面index out of range。排查的话首先检查一下网络和登录等，解决不了再考虑print中间输出，看看再哪一步挂了，当然推荐你直接问[ANormal](https://github.com/ANormalDD)

现在都改好了，非常感谢您抽时间回复，祝学长学业顺利
