### ISSUE TITLE
大佬牛逼

### ISSUE THREAD

**Issue by shsq666** [Zirconium233/yunForNewVerison#3]
有时间研究研究乐跑😂

**Comment by Zirconium233** [comment]
实话说，这个项目的维护我可能都忙不过来，课给排满了，其他事还有一堆。
1. 这个项目主要集中在反编译和获取密钥上，项目包装都是草草了事，基本上就是把自用的测试代码改了一点就发出来了，属于给会python的人一个demo，帮助他们自定义自己的脚本。
2. 未来有空主要也是给这个项目上包装。
3. 乐跑我自己不用，也没有账号，很难做测试。
4. 抓包和反编译的破解思路readme里面已经介绍了，你其实完全可以仿照这个自己搓一个脚本(其实当拿到了反编译代码之后，一切的性质变成了赛博搬砖活)

**Comment by shsq666** [comment]
> 实话说，这个项目的维护我可能都忙不过来，课给排满了，其他事还有一堆。
> 
> 1. 这个项目主要集中在反编译和获取密钥上，项目包装都是草草了事，基本上就是把自用的测试代码改了一点就发出来了，属于给会python的人一个demo，帮助他们自定义自己的脚本。
> 
> 2. 未来有空主要也是给这个项目上包装。
> 
> 3. 乐跑我自己不用，也没有账号，很难做测试。
> 
> 4. 抓包和反编译的破解思路readme里面已经介绍了，你其实完全可以仿照这个自己搓一个脚本(其实当拿到了反编译代码之后，一切的性质变成了赛博搬砖活)

感谢大佬能回复😘
