### ISSUE TITLE
CipherKeyEncrypted和CipherKey是什么关系

### ISSUE THREAD

**Issue by Herbtooth** [Zirconium233/yunForNewVerison#4]
CipherKeyEncrypted和CipherKey是什么关系

**Comment by Zirconium233** [comment]
一般不看github，回的比较慢，抱歉。
1. CipherKeyEncrypted是CipherKey的加密版本，sm2加密，密钥是我提供的sm2公钥。不用encode_sm2现场加密是因为gmssl库和Java hutool库的验签有问题，总不能手搓加密库吧，所以提供了用Java的hutool加密的CipherKeyEncrypted。
2. 反编译的代码发出来是不是侵犯了什么...你给一个邮箱我私发一份dex2jar搞出来的jar文件，当然你要钩出来的原始dex文件也行。

**Comment by Herbtooth** [comment]
预约羽毛球场地约不到，想搞一个预约羽毛球场地的脚本，没有大佬这么强的技术力，最近自己瞎琢磨琢磨 ***@***.***&nbsp;


HerbLee
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月14日(星期四) 中午1:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zirconium233/yunForNewVerison] CipherKeyEncrypted和CipherKey是什么关系 (Issue #4)





 
一般不看github，回的比较慢，抱歉。
  
CipherKeyEncrypted是CipherKey的加密版本，sm2加密，密钥是我提供的sm2公钥。不用encode_sm2现场加密是因为gmssl库和Java hutool库的验签有问题，总不能手搓加密库吧，所以提供了用Java的hutool加密的CipherKeyEncrypted。
 
反编译的代码发出来是不是侵犯了什么...你给一个邮箱我私发一份dex2jar搞出来的jar文件，当然你要钩出来的原始dex文件也行。

**Comment by Herbtooth** [comment]
看了你补充的细节终于看懂了，解出请求参数了，感谢
