### ISSUE TITLE
大佬，想问一下，更新的额外配置中解码数据，解码完的内容为什么会乱码呢

### ISSUE THREAD

**Issue by movexu** [Zirconium233/yunForNewVerison#6]
![IMG_1098](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/5e3143ca-6fd8-4477-91d9-bfefadb5b27b)
![IMG_1099](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/1977465a-bc56-41e5-95a8-2b7951eb35f7)

**Comment by Zirconium233** [comment]
gzip的问题，参见 #5 
```python
KEY_test = b64decode("d4tARxviwcU+f559sqki2A==") # KEY 记得改成那一次的
print(gzip.decompress(decode_sm4("dgcaMEDDH8fv3(example)", KEY_test)).decode())
 # 注意gzip，还有python3是严格区分bytes和string类型的，不能混用，记得decode和encode
```

**Comment by movexu** [comment]
您好，大佬，想问一下这个gzip指的是抓包获取的response body那很长的数据吗

**Comment by Zirconium233** [comment]
你把抓包得到的数据覆盖我给的example字符串，直接运行代码就可以得到解密的数据了，但Key记得换。

**Comment by Zirconium233** [comment]
你把抓包得到的数据覆盖我给的example字符串，直接运行代码就可以得到解密的数据了，但Key记得换。

**Comment by movexu** [comment]
![d7d70ef4237a8b160355f3cfc1311d42](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/51c3da79-344d-40e0-ae88-20ffcdba0f7a)
大佬,请问一下是抓取哪个包的response body

**Comment by movexu** [comment]
![image](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/2c958e34-d670-4010-961d-7f77642fd4dc)
解密16.4kb的得出来这个结果,这个没有坐标

**Comment by Zirconium233** [comment]
你这个包开头一个sunKm总公里数，应该是历史记录主界面的包。你随便找一个跑步记录的包，点开，抓到的哪个就是要的。

**Comment by movexu** [comment]
![image](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/4c196d90-83ef-4f31-8ec5-16e89fde19a5)
这个包应该就是历史记录的包,主要您给的#5的代码我该怎么使用呢,是添加到您给的main函数中使用吗,
![image](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/9727062c-f6ff-4a24-9e46-2a0d079d6e8f)
但是看结果应该是错了,
![image](https://github.com/Zirconium233/yunForNewVerison/assets/161919698/b9d18837-831c-436b-8732-e8daf77077b6)

**Comment by Zirconium233** [comment]
这个代码是给你演示如何用代码里的函数来解密信息的，但你用网页做了这一步。至于你提到的怎么使用信息，readme里面介绍的很详细了，复制粘贴覆盖tasklist.json就行，更细节的直接看代码比较好。

**Comment by movexu** [comment]
谢谢大佬

**Comment by PapiLight** [comment]
> ```python
> gzip
> ```

你好，我想知道你是怎么解密的，卡在解密坐标这一步了。很多网站都解密出错

**Comment by Zirconium233** [comment]
网站解密不动密文很可能是gzip的原因。你就用网站解密一个密钥就行了，写一个python脚本import一下我`decode_sm4`函数，然后把我上面给的代码copy上去，用代码解密。
> > 谢谢大佬
> 
> 你好，我想知道你是怎么解密的，卡在解密坐标这一步了。很多网站都解密出错
