### ISSUE TITLE
现在3.1.1版本抓历史跑步记录包全是乱码

### ISSUE THREAD

**Issue by Cdh0129** [Zirconium233/yunForNewVerison#9]
现在抓历史跑步记录包里面全是乱码，求大佬解惑，不知道是不是方法不对

**Comment by Zirconium233** [comment]
脚本能跑加密就不可能改。你不会是没有解密吧，直接抓是base64编码，解base64再gzip解压缩，再过sm4解密就可以得到正确的结果，示例解密代码见ipynb文件，直接填空跑代码就可以自动导入task。

**Comment by Cdh0129** [comment]
感谢，现在可以了，之前是我搞错了
